### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by shurijoc** [anonymous931/tabatanian#54]
こちらにレビュー内容書かせていただきます！

就活を踏まえて、以下の観点からレビューさせていただきますね！
サービスとREADMEを元にレビューします。

```
💡 就活レビュー観点

1. 課題に対してサービス内で適切な解決策となる機能を提供できているか・READMEに書いているか
2. 就活において十分な技術力を示せる機能を実装しているか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## 1について

> どういったメニューが良いかわからない。
どんな種類のトレーニングがあるのか知らない or 調べるのが億劫

という課題感に対してユーザーに検索させる・調べさせるというユースフローになっているのが気になります。
また、トレーニングタイマー機能もついておりどういった課題を解決したいのかもう一度整理してみていただけますか？

課題→仮説→解決策の3点セットだと納得感が出やすいです。今は課題と解決策はREADMEにある状態なので仮説を書いていただくと良いかなと思います！

## 2について

技術力に関してあと一つ機能を追加したいところです。
技術の観点だけで言えば基本的なRailsのCRUD+少しJSがある状態です。

以下2点、どちらかの機能はいかがでしょうか？（※ そもそもの課題感・仮説・解決策の整理しだいで方向は変わります。）

### 1. RailsのActionCableを使用して、画面右下に「現在トレーニング中の人数」を表示する

タイマー機能があることからも、継続してトレーニングする人向けのサービスという印象があります。
ActionCableはチャットなどで使われるリアルタイムでのデータ通信機能です。

この機能を活用している人は少ないため技術力を見せるには良いかなという印象です。

### 2. トレーニングリマインダー

トレーニングタイマーがあるので完了時にトレーニングの履歴を保存するのはどうでしょうか？
それを使って「その日トレーニングしていない人にはLINE通知などでリマインドする」というような機能です。

## 3について

いきなりトップページから始まり、なんのサイトか・どう使えば良いのかがわかりません。
初回訪問ユーザーにはmodalで https://tabatanian.com/about の中身のような内容を表示するのはどうですか？

どんな方法でも良いのでサービス概要を説明しないと使うのが難しく感じます。

以上、ご確認をお願いします！

**Comment by anonymous931** [comment]
コメントありがとうございます！
以下、コメントに対する回答です。

# 1について
ご指摘いただいた内容を踏まえて、一度、自分が解決したい課題を考え直してみた結果、以下のようになりました。

### 課題

- 自分でトレーニングメニューを考えるのが面倒

- 人気のあるトレーニングメニューを知りたい

- 見つけたトレーニングメニューですぐにトレーニングしたい

### 仮説

- みんながトレーニングメニューを共有するような場所がない

- トレーニングメニューの人気を知る方法がない

- メニューを調べてもトレーニングタイマーが別のアプリなので、メニューを見ながらトレーニングするのが難しい。またアプリを切り替える必要があり、それが手間となる

### 解決策

- トレーニングメニューを投稿し、ソート機能を実装することで人気があるメニューがわかる。また、コメントなどでユーザーの評価を確認できる

- アプリ内にトレーニングタイマーを設定することで、調べたメニューを見ながらすぐにトレーニングできる。

# 2について
追加する機能についてですが、課題にて

> 人気のあるトレーニングメニューを知りたい

という観点から現在、トレーニングをしている人がどのくらいいるのか把握できると、実際にどのくらい使用されていると実感があると思い、

-  RailsのActionCableを使用して、画面右下に「現在トレーニング中の人数」を表示する

こちらの案を使わせていただきたいと思います。

# 3について
こちらはおっしゃる通りだと思いますので、ぜひ実装したいと思います。


以上です。ご確認をお願いします。

**Comment by shurijoc** [comment]
ありがとうございます！

> 1について

こちらとてもスッキリとして何を解決するサービスなのか分かりやすくなりました。とても良いと思います！
READMEの方にもこの3点セットを書くようお願いします！

> 2,3 について
はい、ぜひ実装をお願いします！
ひとまずMVPというところでは現状で大丈夫ですので本リリースまでにこちらの機能をつけていただければと思います！

よろしくお願いします！

![nise_rantekun](https://github.com/anonymous931/tabatanian/assets/6407534/b37a7d49-0a17-4551-960a-b7c697fc939b)

**Comment by anonymous931** [comment]
ありがとうございました！
